### ISSUE TITLE
Movies: no distinction between watched and unwatched

### ISSUE THREAD

**Issue by fallerOfFalls** [michaldrabik/showly-2.0#292]
Movies are either "added to my movies" or just, nothing. There is no setting to get them to appear in "progress".

**Comment by fallerOfFalls** [comment]
Oh, it's the "add to watchlist"/"see later" option. But that's weird because when you use that on shows, it just puts the show in your collection and when you use "add to my shows" it appears in progress. So the same buttons with the same text do the opposite thing for movies than what they do with shows.

**Comment by fallerOfFalls** [comment]
Shows has a distinction between "watchlist" and "progress". I like this. Movies currently treats them as synonymous. I'd love movies to be treated the same as shows, with the two icons to the right of "added to my shows/movies" but this time the button for selecting which episodes you've watched, just toggles whether you've watched the movie. And the archive button as well because why not.

**Comment by michaldrabik** [comment]
Hey,
this is kind of because of the nature of movies vs shows. Naturally Movies cant have "progress" so in that case Progress tab means more like "How am I doing watching films I've added to watchlist. You can treat progress as a shortcut in that case because yeah its basically watchlist but with a quick option to mark movie as watched. 

I don't really plan to change this at the moment :)

**Comment by fallerOfFalls** [comment]
What about just renaming the buttons to be clearer?
"Add to my movies" > "seen it"
"See later" > "add to watchlist"

**Comment by michaldrabik** [comment]
I have actually been considering renaming "See Later" to just "Watchlist" in both Shows and Movies sections.
So might give it another thought.
