### ISSUE TITLE
Custom list petition 

### ISSUE THREAD

**Issue by elvis0288** [michaldrabik/showly-2.0#454]
Hello man,

Loved what you did with the lists. It is so brilliant.. I have a suggestion that not even trakt has. Is it possible to create a sorting option to sort by amount of episodes left? So you know there is by name by rank and so on.. I have a custom list in which I order the TV shows I want to see from the TV show with fewer episodes to the one with more episodes..

**Comment by elvis0288** [comment]
Something like the episodes left you have in progress

**Comment by michaldrabik** [comment]
I feel like it might be something I do not want to do because users lists often consist of hundred of shows and to properly implement such a sort I would need to download tons of data from Trakt (seasons and episodes) that would not really be used at all.

In progress it's possible because in 99% of time it consists only of handful of series.

**Comment by elvis0288** [comment]
that makes sense.. no problem at all. thank you sir
