### ISSUE TITLE
Unwatched is not synced with trakt.tv

### ISSUE THREAD

**Issue by elbowz** [michaldrabik/showly-2.0#456]
Ciao,
 I don't know if this is bug or a feature, but when I uncheck/unselect a episode (maybe for a mistake), this stays watched on trakt.tv.

I have enabled:
* Trakt.tv Instant upload
* Trakt.tv Instant Remove

Also tried to perform a full sync, without obtain the expected result.

A second, and last suggest: an option to add a watched film *Right now* or *Release Date*, maybe through a message box optionally enabled by setting.

Both of them is not really big issues, but your polished app is real amazing! 
Really thanks for you hard work!

**Comment by michaldrabik** [comment]
@elbowz Hi.

This is by design. Unchecking episodes will never remove them from your Trakt.tv (account). 

However if you have "Trakt.tv Instant Remove" enabled the app will ask you if you want to remove the whole show's progress from your account when you remove a show from "My Shows" or if you want to remove if from your Trakt Watchlist when you remove a shows from app's watchlist. Same goes for Movies.

The second thing I already have added in my backlog so I will work on it eventually -> #391

**Comment by elbowz** [comment]
Hi @michaldrabik, 

it's a strange behavior from my point of view...at least for inconsistency between Showly DB and Trakt one. Indeed, I have just discover if i re-check/re-select the episode, trakt.tv increase the number of played.

Anyway it's only my personal use and workflow :)

> However if you have "Trakt.tv Instant Remove" enabled the app will ask you if you want to remove the whole show's progress from your account when you remove a show from "My Shows" or if you want to remove it from your Trakt Watchlist when you remove a show from app's watchlist. Same goes for Movies.

I see, this with the use of *Archive* feature have a logic behind. 

> The second thing I already have added in my backlog so I will work on it eventually -> #391

Great!

Thanks for you speedy and detailed answer...feel free to close the issue ticket.

**Comment by michaldrabik** [comment]
> it's a strange behavior from my point of view...at least for inconsistency between Showly DB and Trakt one. Indeed, I have just discover if i re-check/re-select the episode, trakt.tv increase the number of played.

There were few reasons I've decided to do it that way. One of them was that Showly does not support multiple plays and watches at this moment. So if you uncheck an episode in the app there is no way of knowing if Trakt should remove all historical plays or maybe just a certain one - or just the last one? 

I think 99% percent of typical users will never have to uncheck an episode (it's hard to unwatch something when you have actually seen it :) ) and if you check something by accident there is a 3 seconds buffer before an actual sync intializes so there is still time to uncheck.

If you need to do some advanced operations you can still do it via Trakt.tv website though.

Thanks,
Mike

**Comment by elbowz** [comment]
> So if you uncheck an episode in the app there is no way of knowing if Trakt should remove all historical plays or maybe just a certain one - or just the last one?

Now, it's clear!

> if you check something by accident there is a 3 seconds buffer before an actual sync intializes so there is still time to uncheck.

ahaha...good hint :)

> If you need to do some advanced operations you can still do it via Trakt.tv website though.

Yeah, I agree

Thanks!

**Comment by RokeJulianLockhart** [comment]
@michaldrabik, I don't believe that I can use Showly, due to this. I need to know that what I see on the local database represents the current state of the server. The local client not being as advanced is of less concern than inconsistent state.

I can't even revert an unwatch via manual Trakt synchronisation.
