### ISSUE TITLE
Sync unwatched change

### ISSUE THREAD

**Issue by beam** [michaldrabik/showly-2.0#472]
It is impossible to synchronize the state from the watched ep to the unwatched. When I unmark an episode on trakt.tv, the change will not be synchronized to the application and unmarked episode in app isn't synchronized to web.

**Comment by michaldrabik** [comment]
@beam Hi, yes this is currently by choice.

One of the reasons is because Showly does not support multiple watches at this moment and there would be no way of knowing which history element (or maybe all of them) should be removed from web Trakt account.

If you want to clear your progress though you can enable "Quick Remove" and then when you remove a series from "My Shows" the app will ask you if you also want to remove your whole progress from the Trakt.tv web account.
