### ISSUE TITLE
Next episode on Watchlist sometimes shows S01E01 instead of next episode

### ISSUE THREAD

**Issue by RealLukeManning** [michaldrabik/showly-2.0#55]
I have some shows added such as Family Guy and The Simpsons where I often haven't seen the first few seasons. For example with American Dad I am halfway through season 15 but my Watchlist shows my next episode as S01E01 which is incorrect. I'd rather not mark as watched since that's technically incorrect!

**Comment by michaldrabik** [comment]
Hi. I see your point. I think the app must assume some kind of logical flow of episodes. 
Since it cannot know that how do you plan on watching lets say The Simpsons it has to start tracking starting with the oldest unwatched episode.

When you finish watching season 15 the app have no way of knowing if you will continue with season 16 (display S.16 E.01 as next episode) or will you jump to season 12.

I hope this makes sense?

**Comment by briktor** [comment]
Maybe add an option to mark episodes as skipped?

**Comment by michaldrabik** [comment]
> Maybe add an option to mark episodes as skipped?
@briktor I would like to be consistent with Trakt where I can and there seem not to be such an option there.

**Comment by TigersWay** [comment]
There's an option in Trakt, you simply can hide seasons.
Anyway you can easily guess / your best bet would be that the next episode you'll gonna watch is the one after the last one you've watched.
