### ISSUE TITLE
Problem with shows based on TVDB

### ISSUE THREAD

**Issue by Francy115** [michaldrabik/showly-2.0#570]
It seems like whenever a show's data is based on TVDB translations don't show up, despite being present in the database (e.g. one piece, naruto, kirby, fate/zero, etc...), why?
Same issue for pictures, for instance, one piece has no pictures at all from 2nd season onward, but on TVDB there is everything (on TMDB too, but this show is still based on TVDB)
Is this sort of a bug?

I hope it can be solved, I've spent so much time adding translations and pictures on both TMDB and TVDB and not seeing them is a bit frustrating

**Comment by Francy115** [comment]
I'll post some screenshots:
![OfIvfQe](https://user-images.githubusercontent.com/98353972/152338993-921d826f-4543-4b15-b829-86d3baef36f1.jpg)

This show is One Piece, on Trakt it says it is still based on TVDB. Even though [TVDB ](https://thetvdb.com/series/one-piece/seasons/official/2) has every episode's title translated, they don't appear on showly.

This doesn't only happen just with, but with every language and with every show based on TVDB.

Also, pictures don't appear:
![hgMDI8W](https://user-images.githubusercontent.com/98353972/152339883-81e7c9ee-1a6f-44e0-b5ca-35064e762f4d.jpg)

[Episode's picture](https://thetvdb.com/series/one-piece/episodes/361897) from TVDB

I hope it can be fixed

**Comment by michaldrabik** [comment]
I have investigated One Piece example.
The problem is seasons and episodes sync between Trakt and TMDB.
https://trakt.tv/transition/tmdb/shows?trakt_id=37696

Trakt ditched TVDB completely some time ago and they are migrating everything to TMDB. It seems like One Piece has not done it yet (judging from the link above). So for example Season 2 should have 16 episodes not 22. This results in app image loader not knowing what to do.

I think this need to be addressed via Trakt Support team as Trakt should always match TMDB data - not TVDB.
Also I think these cases should be very rare in general.
