### ISSUE TITLE
Hide NSFW shows

### ISSUE THREAD

**Issue by crxssed7** [michaldrabik/showly-2.0#636]
Sometimes when browsing the discover page there is NSFW shows (specifically in the anime section). See below screenshot (blacked out of course). Is there any way to hide these or at least have an option to hide them?

![Screenshot_20220917-093053_Showly](https://user-images.githubusercontent.com/48864420/190848120-2332b01c-7345-4cc5-b294-b732baf01a68.jpg)

**Comment by crxssed7** [comment]
In hindsight I realise that the screenshot isn't very helpful but I promise that is an NSFW show 😅

**Comment by crxssed7** [comment]
So turns out Trakt [doesn't actually allow NSFW shows](https://support.trakt.tv/support/discussions/topics/70000463098), so I think the way to go forward from here is to just report those shows when I see them.

I'll leave this issue open, just in case you feel there something you can do too in the code.

**Comment by michaldrabik** [comment]
@crxssed7 Thanks and sorry for a late reply.

Yes no NSFW shows/movies should ever appear in Trakt website and Trakt API.
If you see any it should be reported through Trakt.

Not much that can be done in code since Trakt API does not provide any kind of indication for that so It's impossible to filter out.
