### ISSUE TITLE
Showly sync overwrites Watchlist changes made in Trakt

### ISSUE THREAD

**Issue by tomeczeka** [michaldrabik/showly-2.0#719]
**Describe the bug**
1. remove a show from "Watchlist" on web Trakt.tv (which has previously been synced to Showly watchlist)
2. sync Showly as usual (import+export enabled)
3. the show reappears on the Watchlist on Trakt

**Expected behavior**
I expected the show to dissapear from Showly, since deleting it was the latest change made in the Watchlist.
My guess though is that Trakt api does not allow to compare edit times to the Watchlist, so Showly sync is unable to tell whether this show was added in Showly or removed on Trakt.
I imagine you would probably have to keep an extra copy of previously imported Trakt watchlist and then compare it when synchronising?
On the other hand though, the Watchlist does sync in "Recently added" order, so perhaps there is a simpler way to spot web edits?

**Screenshots**
not applicable really

**Comment by michaldrabik** [comment]
Sync is general "additive" and the app treats Trakt as the ultimate source of user data. It will never remove anything until explicitly asked to. 

When app receives results from Trakt API it has no way of knowing, when the show is not present in the response, If the show was removed by user on the web or was is simply never there. That's why since it is present in the app it will be added to Trakt.

If you want to remove show both from the app and Trakt account the best way is to do it via app (with Trakt Remove option enabled in the Settings).

If you first remove content in the Trakt website you will need to also remove it in the app manually.
