### ISSUE TITLE
App requests rate limit

### ISSUE THREAD

**Issue by SodaSurfer** [michaldrabik/showly-2.0#739]
Hi
first I must say it's a great project! good job.

I'm trying to understand something about the app architecture and API rate limiting.
The data that is being displayed in the Discover page, is fetched from Trakt API, but they do not publish images.
So, for every show in the Discover page, the app sends a request to TMDB/OMDB, but it may cause sending tens of requests per seconds doesn't it?
because enough that we scroll a bit in the Discover page, we can see at least 100 shows for example, and if there are more then 100 users doing this simultaneously, it may cause rate limit from TMDB/OMDB.

am I missing something? do we really send a seperate request for every show in the discover page?

thanks

**Comment by michaldrabik** [comment]
Yes currently it is the only way to acquire an image for each of the shows. There is a rate limit but its high enough to not cause any problems: https://developer.themoviedb.org/docs/rate-limiting

Also it's also an initial load only since then the images are cached locally and managed by Glide library
