### ISSUE TITLE
Crash on 3.33.3 (PlayStore)

### ISSUE THREAD

**Issue by mmalisz** [michaldrabik/showly-2.0#802]
**Describe the bug**
Since the update the app crashes.

**Expected behavior**
The app should start as previously.

**Screenshots**
```
FATAL EXCEPTION: Firebase Background Thread #0
Process: com.michaldrabik.showly2, PID: 11253
java.io.IOException: Unable to create parent directories of /data/user/0/com.michaldrabik.showly2/files/datastore/firebase_session_Y29tLm1pY2hhbGRyYWJpay5zaG93bHky_data.preferences_pb
at y0.m0.k(SourceFile:217)
at y0.m0.j(SourceFile:1)
at y0.j0.p(SourceFile:13)
at rn.a.f(SourceFile:1)
at mq.k0.run(SourceFile:1)
at r5.s.run(SourceFile:39)
at sq.i.run(SourceFile:1)
at sq.a.run(SourceFile:92)
Suppressed: rq.h: [t1{Cancelling}@5cca404, n8.e@1333ded]
```

I run LineageOS 20 (Android 13) with microG instead of Google services, with Magisk.

**Comment by michaldrabik** [comment]
Since you are using custom OS and also do not have GServices I expect that unexpected behaviour is to happen and nothing can be done really.

Please try using OSS version which you can get from this repository releases. It is stripped from all Google related stuff (but also does not have premium features).

Should run fine.

**Comment by mmalisz** [comment]
Thanks for the reply.

Is there a way to not lose the data, as I have the progress stored locally only.

**Comment by michaldrabik** [comment]
Interesting I assumed you are new user. To export data for now only way is to create free Trakt account (can be done even with some temp mail) and use export options from within the app. Then use the same account to import.

If you do that you can also clear the app data and see if the crash continues. Since it is related to Firebase I'm nearly sure it is connected with non original Google Services. Perhaps some changes were made on Google side etc.

**Comment by mmalisz** [comment]
Hmm, that was strange.

I've created a backup with [NeoBackup](https://github.com/NeoApplications/Neo-Backup), wiped the Showly's data, opened the app - it worked.

I've restored the backup - it works again!

I guess I can close this issue now.
